#!/usr/bin/env python3
"""Build cubex_dictionary.js from cubex_words.txt."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORDS_FILE = ROOT / "page" / "cubex_words.txt"
OUTPUT_FILE = ROOT / "cubex_dictionary.js"
MIN_LEN = 2
MAX_LEN = 12


def load_words(path: Path) -> list[str]:
    raw = path.read_text(encoding="utf-8")
    tokens = re.split(r"[,\n]+", raw)
    words: list[str] = []
    for token in tokens:
        word = token.strip().strip("[]").upper()
        if word.isalpha() and MIN_LEN <= len(word) <= MAX_LEN:
            words.append(word)
    return sorted(set(words))


def render_dictionary_js(words: list[str]) -> str:
    payload = json.dumps(words, separators=(",", ":"))
    return (
        "// Generated by scripts/build_dictionary.py — do not edit by hand.\n"
        f"const wordSet = new Set({payload});\n"
    )


def build() -> int:
    if not WORDS_FILE.exists():
        print(f"error: missing {WORDS_FILE}", file=sys.stderr)
        return 1

    words = load_words(WORDS_FILE)
    OUTPUT_FILE.write_text(render_dictionary_js(words), encoding="utf-8")
    print(f"Built dictionary: {len(words)} words -> {OUTPUT_FILE}")
    return 0


def check() -> int:
    if not OUTPUT_FILE.exists():
        print(f"error: missing {OUTPUT_FILE}; run build first", file=sys.stderr)
        return 1

    expected = render_dictionary_js(load_words(WORDS_FILE))
    actual = OUTPUT_FILE.read_text(encoding="utf-8")
    if actual != expected:
        print("error: cubex_dictionary.js is out of sync with cubex_words.txt", file=sys.stderr)
        return 1

    print("Dictionary check passed.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Build or verify the Word Cube dictionary.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with error if cubex_dictionary.js does not match cubex_words.txt",
    )
    args = parser.parse_args()
    return check() if args.check else build()


if __name__ == "__main__":
    raise SystemExit(main())
